#!/bin/sh

export RED='\033[0;31m'
export GREEN='\033[0;32m'
export BLUE='\033[0;34m'
export NC='\033[0m'

export SSH_SRV='rh1521@shell1.doc.ic.ac.uk'
export SSH_DIR='~/bu-output'

sleep 1

echo -e "${BLUE}Executing /init script...${NC}"
mount -t devtmpfs dev /dev	# devtmpfs is NOT auto-mounted by kernel in initramfs
mount -t proc proc /proc	# Must mount /proc to mount real root later

echo -e "${RED}Press ENTER to interrupt boot...${NC}"
read -t 1 ans	# 1 seconds delay to wait for input

if [ $? == 0 ]; then
	echo -e "${BLUE}Boot interrupted.${NC}"
	while [ true ]; do
		# Spawn shell with job control on ttyS0
		# For more info, see busybox cttyhack
		setsid sh -c 'exec sh </dev/ttyS0 >/dev/ttyS0 2>&1'
		echo -e "${BLUE}Shell respawned. Use 'reboot -f' or 'halt -f' to restart/shutdown the system.${NC}"
	done
else
	echo -e "${GREEN}Switching from initramfs to real root...${NC}"
	mount /dev/mmcblk0p2 /newroot
	mount --move /dev /newroot/dev
	mount --move /proc /newroot/proc
	exec switch_root -c /dev/ttyS0 /newroot /sbin/init
fi
